aws:
  accessKey: AKIASEWHHNQ76XPFCVNO
  secretKey: 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
  region: us-east-2

cognito:
  user-pool-id: us-east-2_pOEeJ29pX
  app-client-id: 23urohbgla6ji2lh5ue3nr6qeo